consumer-key: "![LNoJZCjqOqYPiFxnW52raU5grAQdCdOZFeyukEUs7isI8QMFy0PIQz+P/yrR5fe3oEd2Bigfj0taY38pGllalhcX3/brVNdFZkvy4tw6Qah3KztCSMPbew==]"
store-password: "![09bNJKGe2rGPRlkO2FkZNg==]"
principal: "![YUGqe2N5r5qSNldLisATcj8FeLpqrFC+kQKE+nzN27I=]"